// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPDUiYVqal9kT-wA8BZmGMMY6UDbTPWCw',
    appId: '1:1007589829804:web:22e2134663f274f601c309',
    messagingSenderId: '1007589829804',
    projectId: 'testclone-dda95',
    authDomain: 'testclone-dda95.firebaseapp.com',
    storageBucket: 'testclone-dda95.firebasestorage.app',
    measurementId: 'G-SSGEPDZW87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhGw5cPjNZA96Tp5TqICX_hOt0Kcy0le0',
    appId: '1:1007589829804:android:b5a03295af62855901c309',
    messagingSenderId: '1007589829804',
    projectId: 'testclone-dda95',
    storageBucket: 'testclone-dda95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxzRbfqGqcws_bhdgYISccLtG_R9P-Ogs',
    appId: '1:1007589829804:ios:d48583fc782ed9c001c309',
    messagingSenderId: '1007589829804',
    projectId: 'testclone-dda95',
    storageBucket: 'testclone-dda95.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxzRbfqGqcws_bhdgYISccLtG_R9P-Ogs',
    appId: '1:1007589829804:ios:d48583fc782ed9c001c309',
    messagingSenderId: '1007589829804',
    projectId: 'testclone-dda95',
    storageBucket: 'testclone-dda95.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPDUiYVqal9kT-wA8BZmGMMY6UDbTPWCw',
    appId: '1:1007589829804:web:b1d9f206e70b3df601c309',
    messagingSenderId: '1007589829804',
    projectId: 'testclone-dda95',
    authDomain: 'testclone-dda95.firebaseapp.com',
    storageBucket: 'testclone-dda95.firebasestorage.app',
    measurementId: 'G-J4HPSNRD6W',
  );
}
